name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm i -g snyk
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: install snyk-to-html
        run: |
          npm install snyk-to-html -g
          snyk test --json | snyk-to-html -o result-sca.html
          mkdir -p results
          cp -v /home/runner/work/nodejs-goof/nodejs-goof/*.html /home/runner/work/nodejs-goof/nodejs-goof/results
          
      - name: Commit back to GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add /home/runner/work/nodejs-goof/nodejs-goof/results/*.html
          git commit -m "Uploading artifact file"
          git push
      
      - name: Display HTML
        run: |
          echo 'https://htmlpreview.github.io/?https://github.com/snyk-marcos/nodejs-goof/blob/master/results/result-sca.html'
      
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results
